//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediTurno.CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medico
    {
        public Medico()
        {
            this.Turno = new HashSet<Turno>();
        }
    
        public int Id { get; set; }
        public int EmpleadoId { get; set; }
        public string Matricula { get; set; }
        public int EspecialidadId { get; set; }
    
        public virtual Empleado Empleado { get; set; }
        public virtual Especialidad Especialidad { get; set; }
        public virtual ICollection<Turno> Turno { get; set; }
    }
}
